# Generated by Django 2.2.5 on 2020-03-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='artist',
            field=models.CharField(default='Imagine Dragons', max_length=150),
            preserve_default=False,
        ),
    ]
