# Generated by Django 2.2.5 on 2020-03-10 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_ownership_user_month_purchased'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='user_month_purchased',
            field=models.CharField(blank=True, choices=[('0', 'January'), ('1', 'Febuary'), ('2', 'March'), ('3', 'April'), ('4', 'May'), ('5', 'June'), ('6', 'July'), ('7', 'August'), ('8', 'September'), ('9', 'October'), ('10', 'November'), ('11', 'December')], default='', max_length=1, null=True),
        ),
    ]
