# Generated by Django 2.2.5 on 2020-03-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20200310_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='month_puchased',
            new_name='month_purchased',
        ),
    ]
